<?php
/**
 * @package The_SEO_Framework\Views\Sitemap\XSL\Styles
 * @subpackage The_SEO_Framework\Sitemap\XSL
 */

// phpcs:disable, VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable -- includes.
// phpcs:disable, WordPress.WP.GlobalVariablesOverride -- This isn't the global scope.

defined( 'THE_SEO_FRAMEWORK_PRESENT' ) and tsf()->_verify_include_secret( $_secret ) or die;

?>
<p>
	<?php
	// phpcs:ignore, WordPress.Security.EscapeOutput.OutputNotEscaped -- convert_markdown escapes.
	echo $this->convert_markdown(
		/* translators: URLs are in Markdown. */
		esc_xml( __( 'Generated by [The SEO Framework](https://theseoframework.com/)', 'autodescription' ) ),
		[ 'a' ],
		[ 'a_internal' => false ]
	);
	?>
</p>
